### ISSUE TITLE
Displaying an effect gets the watermelon model instead

### ISSUE THREAD

**Issue by LOL-DUDE-64** [TextBox75/GMMV#1]
Using either the Model Viewer Tool or the context menu option on an effect displays **watermelon01.mdl** in the model viewer instead of the actual model that was selected.

**Comment by SkyNinja** [comment]
Dealt with this when I ported the model manipulator to the context menu.
Changing [Line 59](https://github.com/TextBox75/GMMV/blob/main/hlmv/lua/autorun/client/modelviewer.lua#L59) of modelviewer.lua to this should fix it.

```
if ( ent:GetClass() == "prop_effect" ) then
	ModelPanel:SetModel(ent.AttachedEntity:GetModel())
else
	ModelPanel:SetModel(ent:GetModel())
end
```
